/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#ffb68a",
        "on-surface-variant": "#c7c5d0",
        "background": "#131317",
        "on-surface": "#e4e1e6",
        "error-container": "#93000a",
        "on-tertiary-container": "#794521",
        "canvas-global": "#070708",
        "on-error-container": "#ffdad6",
        "on-background": "#e4e1e6",
        "secondary": "#50d8e9",
        "border-structural": "#232426",
        "on-error": "#690005",
        "on-primary-container": "#494e83",
        "on-tertiary-fixed": "#321300",
        "on-secondary": "#00363c",
        "secondary-fixed-dim": "#50d8e9",
        "surface": "#131314",
        "surface-container-high": "#2a292d",
        "primary-fixed-dim": "#bec2ff",
        "error": "#ffb4ab",
        "surface-container": "#201f21",
        "primary-fixed": "#e0e0ff",
        "secondary-fixed": "#91f1ff",
        "inverse-on-surface": "#303034",
        "secondary-container": "#00b1c1",
        "primary": "#e0e0ff",
        "on-secondary-container": "#003e44",
        "on-tertiary": "#502403",
        "border-internal": "#1b1c1e",
        "on-tertiary-fixed-variant": "#6c3a17",
        "interactive-primary": "#5e6bff",
        "on-primary-fixed-variant": "#3e4276",
        "on-secondary-fixed": "#001f23",
        "tertiary-container": "#ffb689",
        "surface-container-low": "#1b1b1f",
        "panel-high": "#191a1c",
        "surface-tint": "#bec2ff",
        "canvas-primary": "#080809",
        "surface-container-lowest": "#0e0e11",
        "primary-container": "#bec2ff",
        "on-primary": "#272b5e",
        "on-secondary-fixed-variant": "#004f57",
        "outline": "#91909a",
        "tertiary-fixed": "#ffdbc8",
        "panel-low": "#101112",
        "tertiary": "#ffdbc7",
        "outline-variant": "#46464f",
        "surface-bright": "#39393d",
        "inverse-surface": "#e4e1e6",
        "surface-variant": "#353438",
        "surface-container-highest": "#353438",
        "inverse-primary": "#555a90",
        "surface-dim": "#131317",
        "on-primary-fixed": "#111548",
        "primary-hover": "#7a85ff",
        "warning": "#f7d383",
        "success": "#a1f3c3",
        "border": "#1B1C1E",
        "border-strong": "#232426",
        "text": "#F0F1F2",
        "text-muted": "#9A9DA3"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "xl": "40px",
        "margin-safe": "32px",
        "md": "16px",
        "lg": "24px",
        "sm": "8px",
        "gutter": "20px",
        "xs": "4px",
        "base": "4px"
      },
      fontFamily: {
        "label-sm": ["Inter"],
        "h2": ["Manrope"],
        "mono-data": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "h3": ["Manrope"],
        "h4": ["Manrope"],
        "h1": ["Manrope"],
        sans: ['Inter', 'sans-serif'],
        heading: ['Manrope', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        "label-sm": ["12px", { "lineHeight": "1", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "h2": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.05em", "fontWeight": "520" }],
        "mono-data": ["13px", { "lineHeight": "1", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "1.5", "letterSpacing": "0em", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "1.6", "letterSpacing": "0em", "fontWeight": "400" }],
        "h3": ["24px", { "lineHeight": "1.2", "letterSpacing": "-0.04em", "fontWeight": "520" }],
        "h4": ["18px", { "lineHeight": "1.4", "letterSpacing": "-0.02em", "fontWeight": "520" }],
        "h1": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.05em", "fontWeight": "520" }]
      },
      animation: {
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'float-slow': 'floatSlow 8s ease-in-out infinite',
        'float-med': 'floatMed 6s ease-in-out infinite',
        'scale-in': 'scaleIn 0.2s ease-out',
        'fade-in': 'fadeIn 0.3s ease-out',
        'slide-up': 'slideUp 0.3s ease-out',
      },
      keyframes: {
        floatSlow: {
          '0%, 100%': { transform: 'translateY(0) scale(1)' },
          '50%': { transform: 'translateY(-24px) scale(1.04)' },
        },
        floatMed: {
          '0%, 100%': { transform: 'translateY(0) scale(1)' },
          '50%': { transform: 'translateY(18px) scale(0.97)' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(12px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}
